services:
  mysql:
    image: mysql:8.0
    container_name: flask_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3331:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/database/01_crear_roles.sql:/docker-entrypoint-initdb.d/01_crear_roles.sql
    networks:
      - flask_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "flask_user", "-pflask_password" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: flask_app
    restart: always
    env_file:       
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: flask_db
      DB_USER: flask_user
      DB_PASSWORD: flask_password
      FLASK_ENV: development
      SECRET_KEY: ${SECRET_KEY}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      SECURITY_TOTP_SECRETS: ${SECURITY_TOTP_SECRETS}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      ADMIN_DB_USER: ${ADMIN_DB_USER}
      ADMIN_DB_PASSWORD: ${ADMIN_DB_PASSWORD}
      GERENTE_DB_USER: ${GERENTE_DB_USER}
      GERENTE_DB_PASSWORD: ${GERENTE_DB_PASSWORD}
      PRODUCCION_DB_USER: ${PRODUCCION_DB_USER}
      PRODUCCION_DB_PASSWORD: ${PRODUCCION_DB_PASSWORD}
      CLIENTE_DB_USER: ${CLIENTE_DB_USER}
      CLIENTE_DB_PASSWORD: ${CLIENTE_DB_PASSWORD}
      BACKUP_DB_USER: ${BACKUP_DB_USER}
      BACKUP_DB_PASSWORD: ${BACKUP_DB_PASSWORD}
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - flask_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: flask_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - flask_network

volumes:
  mysql_data:


networks:
  flask_network:
