"""agregar estatus a insumos

Revision ID: 04b5db077bf0
Revises: df1e6436104b
Create Date: 2026-03-25 20:23:33.475247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b5db077bf0'
down_revision = 'df1e6436104b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', name='estatus_insumo_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###
