"""Agregando tablas de empleados, clientes y pedidos

Revision ID: 0b141dc92ff0
Revises: 99f7b9382711
Create Date: 2026-04-01 00:38:36.595138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b141dc92ff0'
down_revision = '99f7b9382711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('uuid_empleado', sa.String(length=36), nullable=False),
    sa.Column('uuid_usuario', sa.String(length=36), nullable=False),
    sa.Column('numero_empleado', sa.String(length=50), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_usuario'], ['usuarios.uuid_usuario'], ),
    sa.PrimaryKeyConstraint('uuid_empleado'),
    sa.UniqueConstraint('numero_empleado'),
    sa.UniqueConstraint('uuid_usuario')
    )
    op.create_table('pedidos_proveedor_encabezado',
    sa.Column('uuid_pedido', sa.String(length=36), nullable=False),
    sa.Column('folio_pedido', sa.String(length=50), nullable=False),
    sa.Column('uuid_proveedor', sa.String(length=36), nullable=False),
    sa.Column('uuid_usuario_solicita', sa.String(length=36), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estatus', sa.Enum('Pendiente', 'Aprobado', 'Parcial', 'Completado', 'Cancelado', name='estatus_pedido_enum'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_proveedor'], ['proveedores.uuid_proveedor'], ),
    sa.ForeignKeyConstraint(['uuid_usuario_solicita'], ['usuarios.uuid_usuario'], ),
    sa.PrimaryKeyConstraint('uuid_pedido'),
    sa.UniqueConstraint('folio_pedido')
    )
    op.create_table('pedidos_proveedor_detalle',
    sa.Column('uuid_detalle_pedido', sa.String(length=36), nullable=False),
    sa.Column('uuid_pedido', sa.String(length=36), nullable=False),
    sa.Column('uuid_insumo', sa.String(length=36), nullable=False),
    sa.Column('cantidad_pedida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('costo_unitario_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['uuid_insumo'], ['insumos.uuid_insumo'], ),
    sa.ForeignKeyConstraint(['uuid_pedido'], ['pedidos_proveedor_encabezado.uuid_pedido'], ),
    sa.PrimaryKeyConstraint('uuid_detalle_pedido')
    )
    with op.batch_alter_table('compras_detalle', schema=None) as batch_op:
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('compras_encabezado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_pedido', sa.String(length=36), nullable=True))
        batch_op.create_index('idx_compra_fecha', ['fecha_compra'], unique=False)
        batch_op.create_foreign_key(None, 'pedidos_proveedor_encabezado', ['uuid_pedido'], ['uuid_pedido'])

    with op.batch_alter_table('ejecucion_corte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_rollo_used', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('metros_teoricos_requeridos', sa.Numeric(precision=12, scale=4), nullable=False))
        batch_op.drop_constraint('ejecucion_corte_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rollos_inventario', ['uuid_rollo_used'], ['uuid_rollo'])
        batch_op.drop_column('uuid_rollo_usado')

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.Enum('ROLLO', 'PIEZA', name='unidad_compra_enum'), nullable=False))
        batch_op.add_column(sa.Column('contenido_cantidad', sa.Numeric(precision=12, scale=4), nullable=False))
        batch_op.add_column(sa.Column('contenido_unidad_medida', sa.Enum('METRO', 'PIEZA', name='unidad_base_enum'), nullable=False))
        batch_op.add_column(sa.Column('ancho', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', name='estatus_insumo_enum'), nullable=True))
        batch_op.drop_column('costo_unitario_individual')

    with op.batch_alter_table('modelos_ropa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ordenes_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_venta_detalle', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'ventas_detalle', ['uuid_venta_detalle'], ['uuid_detalle'])
        batch_op.drop_column('usuario_asigno_uuid')

    with op.batch_alter_table('productos_terminados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('rollos_inventario', schema=None) as batch_op:
        batch_op.drop_column('ancho_real_recibido')

    with op.batch_alter_table('ventas_encabezado', schema=None) as batch_op:
        batch_op.create_index('idx_venta_fecha', ['fecha_venta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas_encabezado', schema=None) as batch_op:
        batch_op.drop_index('idx_venta_fecha')

    with op.batch_alter_table('rollos_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ancho_real_recibido', mysql.DECIMAL(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('productos_terminados', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('ordenes_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_asigno_uuid', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uuid_venta_detalle')

    with op.batch_alter_table('modelos_ropa', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_unitario_individual', mysql.DECIMAL(precision=12, scale=4), nullable=False))
        batch_op.drop_column('estatus')
        batch_op.drop_column('ancho')
        batch_op.drop_column('contenido_unidad_medida')
        batch_op.drop_column('contenido_cantidad')
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('ejecucion_corte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_rollo_usado', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ejecucion_corte_ibfk_2', 'rollos_inventario', ['uuid_rollo_usado'], ['uuid_rollo'])
        batch_op.drop_column('metros_teoricos_requeridos')
        batch_op.drop_column('uuid_rollo_used')

    with op.batch_alter_table('compras_encabezado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_compra_fecha')
        batch_op.drop_column('uuid_pedido')

    with op.batch_alter_table('compras_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', mysql.VARCHAR(length=20), nullable=False))

    op.drop_table('pedidos_proveedor_detalle')
    op.drop_table('pedidos_proveedor_encabezado')
    op.drop_table('empleados')
    # ### end Alembic commands ###
