"""crear tabla proveedores

Revision ID: 5e45963f97e0
Revises: 
Create Date: 2026-03-23 18:47:33.009464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e45963f97e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('uuid_categoria', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estatus_visible', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_creo_uuid', sa.String(length=36), nullable=True),
    sa.Column('usuario_actualizo_uuid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('uuid_categoria')
    )
    op.create_table('proveedores',
    sa.Column('uuid_proveedor', sa.String(length=36), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_creo_uuid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('uuid_proveedor')
    )
    op.create_table('usuarios',
    sa.Column('uuid_usuario', sa.String(length=36), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('Admin', 'Producción', 'Gerente', 'Cliente'), nullable=False),
    sa.Column('estatus', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uuid_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('uuid_cliente', sa.String(length=36), nullable=False),
    sa.Column('uuid_usuario', sa.String(length=36), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion_completa', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_actualizo_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['uuid_usuario'], ['usuarios.uuid_usuario'], ),
    sa.PrimaryKeyConstraint('uuid_cliente'),
    sa.UniqueConstraint('uuid_usuario')
    )
    op.create_table('compras_encabezado',
    sa.Column('uuid_compra', sa.String(length=36), nullable=False),
    sa.Column('folio_factura', sa.String(length=50), nullable=True),
    sa.Column('uuid_proveedor', sa.String(length=36), nullable=False),
    sa.Column('uuid_usuario_registro', sa.String(length=36), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estatus', sa.Enum('Pendiente', 'Recibido', 'Cancelado'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_proveedor'], ['proveedores.uuid_proveedor'], ),
    sa.ForeignKeyConstraint(['uuid_usuario_registro'], ['usuarios.uuid_usuario'], ),
    sa.PrimaryKeyConstraint('uuid_compra')
    )
    op.create_table('insumos',
    sa.Column('uuid_insumo', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('uuid_categoria', sa.String(length=36), nullable=True),
    sa.Column('costo_unitario_individual', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_total_acumulado', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stock_minimo_alerta', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_actualizo_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['uuid_categoria'], ['categorias.uuid_categoria'], ),
    sa.PrimaryKeyConstraint('uuid_insumo'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('modelos_ropa',
    sa.Column('uuid_modelo', sa.String(length=36), nullable=False),
    sa.Column('nombre_modelo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('uuid_categoria', sa.String(length=36), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_categoria'], ['categorias.uuid_categoria'], ),
    sa.PrimaryKeyConstraint('uuid_modelo')
    )
    op.create_table('compras_detalle',
    sa.Column('uuid_detalle_compra', sa.String(length=36), nullable=False),
    sa.Column('uuid_compra', sa.String(length=36), nullable=False),
    sa.Column('uuid_insumo', sa.String(length=36), nullable=False),
    sa.Column('cantidad_comprada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('costo_unitario_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['uuid_compra'], ['compras_encabezado.uuid_compra'], ),
    sa.ForeignKeyConstraint(['uuid_insumo'], ['insumos.uuid_insumo'], ),
    sa.PrimaryKeyConstraint('uuid_detalle_compra')
    )
    op.create_table('productos_terminados',
    sa.Column('uuid_producto', sa.String(length=36), nullable=False),
    sa.Column('uuid_modelo', sa.String(length=36), nullable=False),
    sa.Column('sku_especifico', sa.String(length=50), nullable=False),
    sa.Column('talla', sa.Enum('XSS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'Unica'), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_fisico_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo_alerta', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_modelo'], ['modelos_ropa.uuid_modelo'], ),
    sa.PrimaryKeyConstraint('uuid_producto'),
    sa.UniqueConstraint('sku_especifico')
    )
    op.create_table('ventas_encabezado',
    sa.Column('uuid_venta', sa.String(length=36), nullable=False),
    sa.Column('numero_pedido', sa.String(length=25), nullable=False),
    sa.Column('uuid_cliente', sa.String(length=36), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('estatus_envio', sa.Enum('Procesando', 'Enviado', 'Entregado', 'Devuelto'), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_cliente'], ['clientes.uuid_cliente'], ),
    sa.PrimaryKeyConstraint('uuid_venta'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_table('explosion_materiales_cabecera',
    sa.Column('uuid_explosion', sa.String(length=36), nullable=False),
    sa.Column('uuid_producto', sa.String(length=36), nullable=False),
    sa.Column('instrucciones_proceso', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_producto'], ['productos_terminados.uuid_producto'], ),
    sa.PrimaryKeyConstraint('uuid_explosion'),
    sa.UniqueConstraint('uuid_producto')
    )
    op.create_table('ordenes_produccion',
    sa.Column('uuid_op', sa.String(length=36), nullable=False),
    sa.Column('uuid_producto', sa.String(length=36), nullable=False),
    sa.Column('cantidad_a_producir', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'En Corte', 'Confección', 'Terminado'), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_asigno_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['uuid_producto'], ['productos_terminados.uuid_producto'], ),
    sa.PrimaryKeyConstraint('uuid_op')
    )
    op.create_table('rollos_inventario',
    sa.Column('uuid_rollo', sa.String(length=36), nullable=False),
    sa.Column('uuid_insumo', sa.String(length=36), nullable=False),
    sa.Column('uuid_detalle_compra', sa.String(length=36), nullable=True),
    sa.Column('metraje_inicial', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('metraje_continuo_actual', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ancho_real_recibido', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_detalle_compra'], ['compras_detalle.uuid_detalle_compra'], ),
    sa.ForeignKeyConstraint(['uuid_insumo'], ['insumos.uuid_insumo'], ),
    sa.PrimaryKeyConstraint('uuid_rollo')
    )
    op.create_table('ventas_detalle',
    sa.Column('uuid_detalle', sa.String(length=36), nullable=False),
    sa.Column('uuid_venta', sa.String(length=36), nullable=False),
    sa.Column('uuid_producto', sa.String(length=36), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_historico', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['uuid_producto'], ['productos_terminados.uuid_producto'], ),
    sa.ForeignKeyConstraint(['uuid_venta'], ['ventas_encabezado.uuid_venta'], ),
    sa.PrimaryKeyConstraint('uuid_detalle')
    )
    op.create_table('ejecucion_corte',
    sa.Column('uuid_corte', sa.String(length=36), nullable=False),
    sa.Column('uuid_op', sa.String(length=36), nullable=False),
    sa.Column('uuid_rollo_usado', sa.String(length=36), nullable=False),
    sa.Column('metros_sacados_bodega', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('prendas_reales_logradas', sa.Integer(), nullable=False),
    sa.Column('merma_real_calculada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fecha_proceso', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_corto_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['uuid_op'], ['ordenes_produccion.uuid_op'], ),
    sa.ForeignKeyConstraint(['uuid_rollo_usado'], ['rollos_inventario.uuid_rollo'], ),
    sa.PrimaryKeyConstraint('uuid_corte')
    )
    op.create_table('explosion_materiales_detalle',
    sa.Column('uuid_detalle', sa.String(length=36), nullable=False),
    sa.Column('uuid_explosion', sa.String(length=36), nullable=False),
    sa.Column('uuid_insumo', sa.String(length=36), nullable=False),
    sa.Column('consumo_teorico_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ancho_referencia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['uuid_explosion'], ['explosion_materiales_cabecera.uuid_explosion'], ),
    sa.ForeignKeyConstraint(['uuid_insumo'], ['insumos.uuid_insumo'], ),
    sa.PrimaryKeyConstraint('uuid_detalle')
    )
    op.create_table('retazos_inventario',
    sa.Column('uuid_retazo', sa.String(length=36), nullable=False),
    sa.Column('uuid_rollo_origen', sa.String(length=36), nullable=False),
    sa.Column('uuid_corte_origen', sa.String(length=36), nullable=False),
    sa.Column('metraje', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('motivo_merma', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_corte_origen'], ['ejecucion_corte.uuid_corte'], ),
    sa.ForeignKeyConstraint(['uuid_rollo_origen'], ['rollos_inventario.uuid_rollo'], ),
    sa.PrimaryKeyConstraint('uuid_retazo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retazos_inventario')
    op.drop_table('explosion_materiales_detalle')
    op.drop_table('ejecucion_corte')
    op.drop_table('ventas_detalle')
    op.drop_table('rollos_inventario')
    op.drop_table('ordenes_produccion')
    op.drop_table('explosion_materiales_cabecera')
    op.drop_table('ventas_encabezado')
    op.drop_table('productos_terminados')
    op.drop_table('compras_detalle')
    op.drop_table('modelos_ropa')
    op.drop_table('insumos')
    op.drop_table('compras_encabezado')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('categorias')
    # ### end Alembic commands ###
