"""se agrego a insumo el campo de ancho

Revision ID: 8a3749ccbc97
Revises: df960af945de
Create Date: 2026-03-30 18:44:55.991145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3749ccbc97'
down_revision = 'df960af945de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ancho', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_column('ancho')

    # ### end Alembic commands ###
