"""describe el cambio

Revision ID: 99f7b9382711
Revises: b65c81d529dd
Create Date: 2026-03-26 19:57:19.020648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f7b9382711'
down_revision = 'b65c81d529dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tf_phone_number', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tf_phone_number')

    # ### end Alembic commands ###
