"""quitar unidad en compra detalle y agregarla en insumo

Revision ID: df1e6436104b
Revises: c6b8a86b1e01
Create Date: 2026-03-25 19:01:59.610080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df1e6436104b'
down_revision = 'c6b8a86b1e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras_detalle', schema=None) as batch_op:
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.Enum('METRO', 'PIEZA', name='unidad_medida_enum'), nullable=False))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tf_primary_method', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tf_totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('estatus')
        batch_op.drop_column('rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', mysql.ENUM('Admin', 'Producción', 'Gerente', 'Cliente'), nullable=False))
        batch_op.add_column(sa.Column('estatus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('tf_totp_secret')
        batch_op.drop_column('tf_primary_method')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('active')
        batch_op.drop_column('password')

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_column('unidad_medida')

    with op.batch_alter_table('compras_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
