from app.blueprints.usuarios import usuarios_bp
from app.blueprints.security import security_bp
from app.blueprints.catalog import catalog_bp
from app.blueprints.checkout import checkout_bp
from app.blueprints.insumos import insumos_bp
from app.blueprints.categorias import categorias_bp
from app.blueprints.compras import compras_bp
from app.blueprints.inventario import inventario_bp
from app.blueprints.recetas import recetas_bp
from app.blueprints.modelo import modelos_bp